object Libs {
    const val ACTIVITY_COMPOSE = "androidx.activity:activity-compose"
    const val COIL = "io.coil-kt:coil"
    const val COIL_COMPOSE = "io.coil-kt:coil-compose"
    const val COMPOSE_MATERIAL = "androidx.compose.material:material"
    const val COMPOSE_UI = "androidx.compose.ui:ui"
    const val COMPOSE_UI_TOOLING = "androidx.compose.ui:ui-tooling"
    const val COMPOSE_UI_TOOLING_PREVIEW = "androidx.compose.ui:ui-tooling-preview"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val LIFECYCLE_RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor"
    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val RETROFIT_GSON_CONVERTER = "com.squareup.retrofit2:converter-gson"
    const val TIMBER = "com.jakewharton.timber:timber"
}