version: 2
jobs:
  build:
    working_directory: ~/ComposeTemplate
    docker:
      - image: cimg/android:2022.09
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      #      - run:
      #          name: Run Tests
      #          command: ./gradlew lint test
      #      - store_artifacts:
      #          path: app/build/reports
      #          destination: reports
      #      - store_test_results:
      #          path: app/build/test-results
      - run:
          name: Check Dependency Updates
          command: ./gradlew dependencyUpdates -Drevision=release -DoutputFormatter=plain
      - run:
          name: Build Binaries
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apk