version: 2.1
orbs:
  slack: circleci/slack@4.10.1
jobs:
  build:
    working_directory: ~/ComposeTemplate
    docker:
      - image: cimg/android:2022.09
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      #      - run:
      #          name: Run Tests
      #          command: ./gradlew lint test
      #      - store_artifacts:
      #          path: app/build/reports
      #          destination: reports
      #      - store_test_results:
      #          path: app/build/test-results
      - run:
          name: Check Dependency Updates
          command: ./gradlew dependencyUpdates -Drevision=release -DoutputFormatter=plain
      - run:
          name: Set Build Properties
          command: sudo chmod +x ./setBuildProperties; ./setBuildProperties $CIRCLE_BUILD_NUM "1.0.0"  "androiddebugkey" "android" "debug.keystore" "android"
      - run:
          name: Build Binaries
          command: ./gradlew assembleRelease;mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/ComposeTemplateM2-release-${CIRCLE_BUILD_NUM}.apk
      - slack/notify:
          channel: $SLACK_ACCESS_TOKEN_M2
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: $SLACK_ACCESS_TOKEN_M2
          event: pass
          template: basic_success_1
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: apk