version: 2
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    working_directory: ~/ComposeTemplate
    docker:
      - image: cimg/android:2022.09
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
      #      - run:
      #          name: Run Tests
      #          command: ./gradlew lint test
      #      - store_artifacts:
      #          path: app/build/reports
      #          destination: reports
      #      - store_test_results:
      #          path: app/build/test-results
      - run:
          name: Check Dependency Updates
          command: ./gradlew dependencyUpdates -Drevision=release -DoutputFormatter=plain
      - run:
          name: Set Build Properties
          command: sudo chmod +x ./setBuildProperties; ./setBuildProperties $CIRCLE_BUILD_NUM "1.0.0"
      - run:
          name: Build Binaries
          command: ./gradlew assembleDebug;mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/ComposeTemplateM3-debug-${CIRCLE_BUILD_NUM}.apk
      - slack/notify:
          channel: C047ZRMCKFE
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C047ZRMCKFE
          event: pass
          template: basic_success_1
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apk